In [2]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [3]:
(X_train, Y_train), (X_test, Y_test) = keras.datasets.mnist.load_data()

In [5]:
X_train.shape

(60000, 28, 28)

In [6]:
len(X_test)

10000

In [7]:
X_train = X_train / 255
X_test = X_test / 255
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [8]:
#here we will flatten the 2D array of pixels
X_train_flattened = X_train.reshape(len(X_train), 28*28)
X_test_flattened = X_test.reshape(len(X_test), 28*28)

In [9]:
X_train_flattened.shape

(60000, 784)

In [10]:
model = keras.Sequential([
    keras.layers.Dense(10, input_shape=(784,), activation="sigmoid")
])

model.compile(
    optimizer = 'adam',
    loss="sparse_categorical_crossentropy",
    metrics = ['accuracy']
)
model.fit(X_train_flattened, Y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4708 - accuracy: 0.8784
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3038 - accuracy: 0.9160
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2834 - accuracy: 0.9209
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2732 - accuracy: 0.9236
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2666 - accuracy: 0.9260


In [11]:
y_predicted = model.predict(X_test_flattened)
y_predicted[0]

313/313 [==============================] - 1s 2ms/step


array([3.0803965e-02, 1.8132079e-07, 4.5962423e-02, 9.6693367e-01,
       2.0796747e-03, 1.2231267e-01, 1.5538164e-06, 9.9973917e-01,
       9.6434884e-02, 6.5873718e-01], dtype=float32)

In [12]:
np.argmax(y_predicted[0])

7

In [13]:
y_predicted_labels = [np.argmax(i) for i in y_predicted]
y_predicted_labels[:5]

[7, 2, 1, 0, 4]

In [15]:
Y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [19]:
cm = tf.math.confusion_matrix(labels=Y_test, predictions=y_predicted_labels)
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 967,    0,    1,    2,    0,    4,    3,    2,    1,    0],
       [   0, 1112,    3,    2,    0,    2,    4,    2,   10,    0],
       [  11,    8,  917,   18,   11,    2,   13,   10,   36,    6],
       [   5,    0,   14,  925,    0,   25,    2,   10,   18,   11],
       [   2,    1,    2,    1,  899,    0,   12,    4,    8,   53],
       [  12,    1,    2,   32,    7,  783,   17,    4,   27,    7],
       [  15,    3,    7,    1,    7,   11,  911,    2,    1,    0],
       [   2,    5,   20,    9,    7,    0,    0,  939,    4,   42],
       [  10,    8,    7,   26,    8,   30,   10,    9,  849,   17],
       [  11,    5,    1,    9,   14,    7,    0,   12,    6,  944]])>

In [ ]:
#this model has an accuracy of ~92%